environment:
  OBS_STUDIO_VERSION: 19.0.2
  CURL_VERSION: 7.39.0
  QTDIR32: C:\projects\Qt5.7.0\msvc2013
  QTDIR64: C:\projects\Qt5.7.0\msvc2013_64
  DepsPath32: C:\projects\dependencies2013\win32
  DepsPath64: C:\projects\dependencies2013\win64
  build_config: Release

install:
  - git submodule update --init --recursive
  - 'call appveyor.cmd qt570'
  - 'call appveyor.cmd obs-studio-build'
  - 'call appveyor.cmd obs-websocket-build'

build_script:
  - call msbuild /m /p:Configuration=%build_config% C:\projects\obs-websocket\build32\obs-websocket.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - call msbuild /m /p:Configuration=%build_config% C:\projects\obs-websocket\build64\obs-websocket.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

before_deploy:
  - 7z a "C:\projects\obs-websocket\build.zip" C:\projects\obs-websocket\release\*

deploy_script:
  - ps: Push-AppveyorArtifact "C:\projects\obs-websocket\build.zip" -FileName "obs-websocket-$(git log --pretty=format:'%h' -n 1).zip"

test: off

cache:
  - C:\projects\Qt5.7.0\msvc2013
  - C:\projects\Qt5.7.0\msvc2013_64
  - C:\projects\obs-studio -> appveyor.yml